/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package speedtyping;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import javax.swing.JFrame;
import javax.swing.JLabel;


import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.font.TextAttribute;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.text.DecimalFormat;
import java.util.*;
import java.util.List;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;
import javax.sound.sampled.LineUnavailableException;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;


/**
 *
 * @author Server
 */
class GameScreen extends javax.swing.JFrame {

    public GameScreen() {
        
        
        initComponents();
       
        this.setMagicWord(this.magicWord());

        setTitle("Type Mania - Speed Typing");
        
//        List<String> letters = Arrays.asList("1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Z", "X", "C", "V", "B", "N", "M");
//        
//        for (int i = 0; i < letters.size(); i++){
//            String index = "_".equals(letters.get(i)) ? " " : letters.get(i);
//            JButton btn = new JButton("btn_"+ index);
//            btnNewList.put("btn_"+ index, btn);
//        }
        

        heartList.put("heart_1", heart_1);
        heartList.put("heart_2", heart_2);
        heartList.put("heart_3", heart_3);
        heartList.put("heart_4", heart_4);
        heartList.put("heart_5", heart_5);
        heartList.put("heart_6", heart_6);
        heartList.put("heart_7", heart_7);
        heartList.put("heart_8", heart_8);
        

        printTimer();
        startTimer();
        changeTextSettings();
    }
    
    private  void changeTextSettings(){
        
        randomTextLabel.setText(getMagicWord());
        Map<TextAttribute, Object> attributes = new HashMap<TextAttribute, Object>();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        attributes.put(TextAttribute.TRACKING, 1.2);
        attributes.put(TextAttribute.SIZE, 26);
        
        randomTextLabel.setFont(randomTextLabel.getFont().deriveFont(attributes));
        
    }
    
    
    static String AppName = "Type Mania - Speed Typing";
    private static JFrame ScreenMap = new JFrame(AppName);
    
    //private static HashMap<String, JLabel> JLabelObject = new HashMap<String, JLabel>();
    static int screenWidth = 630;
    static int screenHeight = 730;
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_coins = new javax.swing.JLabel();
        jPanel_heart = new javax.swing.JPanel();
        heart_1 = new javax.swing.JLabel();
        heart_2 = new javax.swing.JLabel();
        heart_3 = new javax.swing.JLabel();
        heart_4 = new javax.swing.JLabel();
        heart_5 = new javax.swing.JLabel();
        heart_6 = new javax.swing.JLabel();
        heart_7 = new javax.swing.JLabel();
        heart_8 = new javax.swing.JLabel();
        bg_heart = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        logo_stiwnu = new javax.swing.JLabel();
        logo_cict = new javax.swing.JLabel();
        timerLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_Q = new javax.swing.JButton();
        btn_W = new javax.swing.JButton();
        btn_E = new javax.swing.JButton();
        btn_R = new javax.swing.JButton();
        btn_T = new javax.swing.JButton();
        btn_Y = new javax.swing.JButton();
        btn_U = new javax.swing.JButton();
        btn_I = new javax.swing.JButton();
        btn_O = new javax.swing.JButton();
        btn_P = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_A = new javax.swing.JButton();
        btn_S = new javax.swing.JButton();
        btn_D = new javax.swing.JButton();
        btn_F = new javax.swing.JButton();
        btn_G = new javax.swing.JButton();
        btn_H = new javax.swing.JButton();
        btn_J = new javax.swing.JButton();
        btn_K = new javax.swing.JButton();
        btn_L = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_Z = new javax.swing.JButton();
        btn_X = new javax.swing.JButton();
        btn_C = new javax.swing.JButton();
        btn_V = new javax.swing.JButton();
        btn_B = new javax.swing.JButton();
        btn_N = new javax.swing.JButton();
        btn_M = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_ = new javax.swing.JButton();
        btnList.put("btn_", btn_);
        jLayeredPane1 = new javax.swing.JLayeredPane();
        char_1 = new javax.swing.JLabel();
        char_2 = new javax.swing.JLabel();
        char_3 = new javax.swing.JLabel();
        char_4 = new javax.swing.JLabel();
        char_5 = new javax.swing.JLabel();
        char_6 = new javax.swing.JLabel();
        char_7 = new javax.swing.JLabel();
        char_8 = new javax.swing.JLabel();
        randomTextLabel = new java.awt.Label();
        background = new javax.swing.JLabel();
        hiddenButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(randomTextLabel.getFont());
        setMaximumSize(new java.awt.Dimension(666, 730));
        setMinimumSize(new java.awt.Dimension(666, 730));
        setName("GameScreen"); // NOI18N
        setPreferredSize(new java.awt.Dimension(650, 730));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_coins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speedtyping/assets/score_board_2.png"))); // NOI18N
        getContentPane().add(bg_coins, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jPanel_heart.setFocusable(false);
        jPanel_heart.setOpaque(false);
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 5);
        flowLayout1.setAlignOnBaseline(true);
        jPanel_heart.setLayout(flowLayout1);

        heart_1.setBackground(new java.awt.Color(255, 255, 255));
        heart_1.setForeground(new java.awt.Color(255, 255, 255));
        heart_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speedtyping/assets/heart_a.png"))); // NOI18N
        heart_1.setPreferredSize(new java.awt.Dimension(25, 21));
        jPanel_heart.add(heart_1);
        heart_1.getAccessibleContext().setAccessibleName("heart_1");

        heart_2.setBackground(new java.awt.Color(255, 255, 255));
        heart_2.setForeground(new java.awt.Color(255, 255, 255));
        heart_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speedtyping/assets/heart_a.png"))); // NOI18N
        heart_2.setPreferredSize(new java.awt.Dimension(25, 21));
        jPanel_heart.add(heart_2);
        heart_2.getAccessibleContext().setAccessibleName("heart_2");

        heart_3.setBackground(new java.awt.Color(255, 255, 255));
        heart_3.setForeground(new java.awt.Color(255, 255, 255));
        heart_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speedtyping/assets/heart_a.png"))); // NOI18N
        heart_3.setPreferredSize(new java.awt.Dimension(25, 21));
        jPanel_heart.add(heart_3);
        heart_3.getAccessibleContext().setAccessibleName("heart_3");

        heart_4.setBackground(new java.awt.Color(255, 255, 255));
        heart_4.setForeground(new java.awt.Color(255, 255, 255));
        heart_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speedtyping/assets/heart_a.png"))); // NOI18N
        heart_4.setPreferredSize(new java.awt.Dimension(25, 21));
        jPanel_heart.add(heart_4);
        heart_4.getAccessibleContext().setAccessibleName("heart_4");

        heart_5.setBackground(new java.awt.Color(255, 255, 255));
        heart_5.setForeground(new java.awt.Color(255, 255, 255));
        heart_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speedtyping/assets/heart_a.png"))); // NOI18N
        heart_5.setPreferredSize(new java.awt.Dimension(25, 21));
        jPanel_heart.add(heart_5);
        heart_5.getAccessibleContext().setAccessibleName("heart_5");

        heart_6.setBackground(new java.awt.Color(255, 255, 255));
        heart_6.setForeground(new java.awt.Color(255, 255, 255));
        heart_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speedtyping/assets/heart_a.png"))); // NOI18N
        heart_6.setPreferredSize(new java.awt.Dimension(25, 21));
        jPanel_heart.add(heart_6);
        heart_6.getAccessibleContext().setAccessibleName("heart_6");

        heart_7.setBackground(new java.awt.Color(255, 255, 255));
        heart_7.setForeground(new java.awt.Color(255, 255, 255));
        heart_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speedtyping/assets/heart_a.png"))); // NOI18N
        heart_7.setPreferredSize(new java.awt.Dimension(25, 21));
        jPanel_heart.add(heart_7);
        heart_7.getAccessibleContext().setAccessibleName("heart_7");

        heart_8.setBackground(new java.awt.Color(255, 255, 255));
        heart_8.setForeground(new java.awt.Color(255, 255, 255));
        heart_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speedtyping/assets/heart_a.png"))); // NOI18N
        heart_8.setPreferredSize(new java.awt.Dimension(25, 21));
        jPanel_heart.add(heart_8);
        heart_8.getAccessibleContext().setAccessibleName("heart_8");

        getContentPane().add(jPanel_heart, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 16, 220, 30));

        bg_heart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speedtyping/assets/heart_bg.png"))); // NOI18N
        getContentPane().add(bg_heart, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        author.setBackground(new java.awt.Color(255, 255, 255));
        author.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        author.setText("<html><div style=\"text-align:center; width: 200px;\">Russell C. Pabon - Lead Programmer<br/>Dave D. Postrero - Project Manager<br/>John Revin L. Aurelio - Researcher</div></html>");
        author.setToolTipText("");
        author.setFocusable(false);
        author.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        author.setOpaque(true);
        author.setRequestFocusEnabled(false);
        author.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 260, 70));

        logo_stiwnu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speedtyping/assets/STI-WNU.png"))); // NOI18N
        getContentPane().add(logo_stiwnu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, -1, -1));

        logo_cict.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speedtyping/assets/CICT.png"))); // NOI18N
        getContentPane().add(logo_cict, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, -1, -1));

        timerLabel.setBackground(new java.awt.Color(0, 0, 0));
        timerLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timerLabel.setForeground(new java.awt.Color(255, 255, 255));
        timerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timerLabel.setText("03:00");
        timerLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        timerLabel.setOpaque(true);
        getContentPane().add(timerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 16, 90, 30));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        btn_1.setText("1");
        btn_1.setActionCommand("");
        btn_1.setFocusable(false);
        btn_1.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_1", btn_1);
        jPanel1.add(btn_1);

        btn_2.setText("2");
        btn_2.setActionCommand("");
        btn_2.setFocusable(false);
        btn_2.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_2", btn_2);
        jPanel1.add(btn_2);

        btn_3.setText("3");
        btn_3.setActionCommand("");
        btn_3.setFocusable(false);
        btn_3.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_3", btn_3);
        jPanel1.add(btn_3);

        btn_4.setText("4");
        btn_4.setActionCommand("");
        btn_4.setFocusable(false);
        btn_4.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_4", btn_4);
        jPanel1.add(btn_4);

        btn_5.setText("5");
        btn_5.setActionCommand("");
        btn_5.setFocusable(false);
        btn_5.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_5", btn_5);
        jPanel1.add(btn_5);

        btn_6.setText("6");
        btn_6.setActionCommand("");
        btn_6.setFocusable(false);
        btn_6.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_6", btn_6);
        jPanel1.add(btn_6);

        btn_7.setText("7");
        btn_7.setActionCommand("");
        btn_7.setFocusable(false);
        btn_7.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_7", btn_7);
        jPanel1.add(btn_7);

        btn_8.setText("8");
        btn_8.setActionCommand("");
        btn_8.setFocusable(false);
        btn_8.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_8", btn_8);
        jPanel1.add(btn_8);

        btn_9.setText("9");
        btn_9.setActionCommand("");
        btn_9.setFocusable(false);
        btn_9.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_9", btn_9);
        jPanel1.add(btn_9);

        btn_0.setText("0");
        btn_0.setActionCommand("");
        btn_0.setFocusable(false);
        btn_0.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_0", btn_0);
        jPanel1.add(btn_0);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 610, -1));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        btn_Q.setText("Q");
        btn_Q.setActionCommand("");
        btn_Q.setFocusable(false);
        btn_Q.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_Q.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_Q", btn_Q);
        jPanel3.add(btn_Q);

        btn_W.setText("W");
        btn_W.setActionCommand("");
        btn_W.setFocusable(false);
        btn_W.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_W.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_W", btn_W);
        jPanel3.add(btn_W);

        btn_E.setText("E");
        btn_E.setActionCommand("");
        btn_E.setFocusable(false);
        btn_E.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_E.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_E", btn_E);
        jPanel3.add(btn_E);

        btn_R.setText("R");
        btn_R.setActionCommand("");
        btn_R.setFocusable(false);
        btn_R.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_R.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_R", btn_R);
        jPanel3.add(btn_R);

        btn_T.setText("T");
        btn_T.setActionCommand("");
        btn_T.setFocusable(false);
        btn_T.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_T.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_T", btn_T);
        jPanel3.add(btn_T);

        btn_Y.setText("Y");
        btn_Y.setActionCommand("");
        btn_Y.setFocusable(false);
        btn_Y.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_Y.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_Y", btn_Y);
        jPanel3.add(btn_Y);

        btn_U.setText("U");
        btn_U.setActionCommand("");
        btn_U.setFocusable(false);
        btn_U.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_U.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_U", btn_U);
        jPanel3.add(btn_U);

        btn_I.setText("I");
        btn_I.setActionCommand("");
        btn_I.setFocusable(false);
        btn_I.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_I.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_I", btn_I);
        jPanel3.add(btn_I);

        btn_O.setText("O");
        btn_O.setActionCommand("");
        btn_O.setFocusable(false);
        btn_O.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_O.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_O", btn_O);
        jPanel3.add(btn_O);

        btn_P.setText("P");
        btn_P.setActionCommand("");
        btn_P.setFocusable(false);
        btn_P.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_P.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_P", btn_P);
        jPanel3.add(btn_P);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 610, -1));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        btn_A.setText("A");
        btn_A.setActionCommand("");
        btn_A.setFocusable(false);
        btn_A.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_A.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_A", btn_A);
        jPanel2.add(btn_A);

        btn_S.setText("S");
        btn_S.setActionCommand("");
        btn_S.setFocusable(false);
        btn_S.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_S.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_S", btn_S);
        jPanel2.add(btn_S);

        btn_D.setText("D");
        btn_D.setActionCommand("");
        btn_D.setFocusable(false);
        btn_D.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_D.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_D", btn_D);
        jPanel2.add(btn_D);

        btn_F.setText("F");
        btn_F.setActionCommand("");
        btn_F.setFocusable(false);
        btn_F.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_F.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_F", btn_F);
        jPanel2.add(btn_F);

        btn_G.setText("G");
        btn_G.setActionCommand("");
        btn_G.setFocusable(false);
        btn_G.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_G.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_G", btn_G);
        jPanel2.add(btn_G);

        btn_H.setText("H");
        btn_H.setActionCommand("");
        btn_H.setFocusable(false);
        btn_H.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_H.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_H", btn_H);
        jPanel2.add(btn_H);

        btn_J.setText("J");
        btn_J.setActionCommand("");
        btn_J.setFocusable(false);
        btn_J.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_J.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_J", btn_J);
        jPanel2.add(btn_J);

        btn_K.setText("K");
        btn_K.setActionCommand("");
        btn_K.setFocusable(false);
        btn_K.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_K.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_K", btn_K);
        jPanel2.add(btn_K);

        btn_L.setText("L");
        btn_L.setActionCommand("");
        btn_L.setFocusable(false);
        btn_L.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_L.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_L", btn_L);
        jPanel2.add(btn_L);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 610, 40));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        btn_Z.setText("Z");
        btn_Z.setActionCommand("");
        btn_Z.setFocusable(false);
        btn_Z.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_Z.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_Z", btn_Z);
        jPanel4.add(btn_Z);

        btn_X.setText("X");
        btn_X.setActionCommand("");
        btn_X.setFocusable(false);
        btn_X.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_X.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_X", btn_X);
        jPanel4.add(btn_X);

        btn_C.setText("C");
        btn_C.setActionCommand("");
        btn_C.setFocusable(false);
        btn_C.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_C.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_C", btn_C);
        jPanel4.add(btn_C);

        btn_V.setText("V");
        btn_V.setActionCommand("");
        btn_V.setFocusable(false);
        btn_V.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_V.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_V", btn_V);
        jPanel4.add(btn_V);

        btn_B.setText("B");
        btn_B.setActionCommand("");
        btn_B.setFocusable(false);
        btn_B.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_B.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_B", btn_B);
        jPanel4.add(btn_B);

        btn_N.setText("N");
        btn_N.setActionCommand("");
        btn_N.setFocusable(false);
        btn_N.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_N.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_N", btn_N);
        jPanel4.add(btn_N);

        btn_M.setText("M");
        btn_M.setActionCommand("");
        btn_M.setFocusable(false);
        btn_M.setPreferredSize(new java.awt.Dimension(56, 36));
        btn_M.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        btnList.put("btn_M", btn_M);
        jPanel4.add(btn_M);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 610, 40));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        btn_.setFocusable(false);
        btn_.setPreferredSize(new java.awt.Dimension(360, 36));
        btn_.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        jPanel5.add(btn_);

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 610, 40));

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 2));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 14, 5));

        char_1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        char_1.setForeground(java.awt.Color.darkGray);
        char_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        char_1.setText("A");
        jLayeredPane1.add(char_1);

        char_2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        char_2.setForeground(java.awt.Color.darkGray);
        char_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        char_2.setText("A");
        jLayeredPane1.add(char_2);

        char_3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        char_3.setForeground(java.awt.Color.darkGray);
        char_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        char_3.setText("A");
        jLayeredPane1.add(char_3);

        char_4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        char_4.setForeground(java.awt.Color.darkGray);
        char_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        char_4.setText("A");
        jLayeredPane1.add(char_4);

        char_5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        char_5.setForeground(java.awt.Color.darkGray);
        char_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        char_5.setText("A");
        jLayeredPane1.add(char_5);

        char_6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        char_6.setForeground(java.awt.Color.darkGray);
        char_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        char_6.setText("A");
        jLayeredPane1.add(char_6);

        char_7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        char_7.setForeground(java.awt.Color.darkGray);
        char_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        char_7.setText("A");
        jLayeredPane1.add(char_7);

        char_8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        char_8.setForeground(java.awt.Color.darkGray);
        char_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        char_8.setText("A");
        jLayeredPane1.add(char_8);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 240, 670, 50));

        randomTextLabel.setAlignment(java.awt.Label.CENTER);
        randomTextLabel.setBackground(java.awt.Color.white);
        randomTextLabel.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        randomTextLabel.setForeground(java.awt.Color.darkGray);
        randomTextLabel.setText(getMagicWord());
        randomTextLabel.setVisible(false);
        getContentPane().add(randomTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 650, 50));
        randomTextLabel.getAccessibleContext().setAccessibleName("label_randomText");

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speedtyping/assets/background_small.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        hiddenButton.setText("hiddenButton");
        hiddenButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPressed(evt);
            }
        });
        getContentPane().add(hiddenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String filePath = "Keyboard.wav";
        
    static HashMap<String, JButton> btnNewList = new HashMap<String, JButton>();
    static HashMap<String, JButton> btnList = new HashMap<String, JButton>();
    static HashMap<String, JLabel> heartList = new HashMap<String, JLabel>();
    
    
    
       private static int heartLife = 8;

    
    
    public  Clip playMusic(String file) {
        
        try {
            
            Clip clip = AudioSystem.getClip();
            
            try {
                
                
                //AudioInputStream inputStream = AudioSystem.getAudioInputStream(LoginScreen.class.getResourceAsStream(file));
                //getClass().getResource(file);
                AudioInputStream inputStream = AudioSystem.getAudioInputStream(getClass().getResource(file));
                
                clip.open(inputStream);
                //FloatControl gainControl = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN);
                FloatControl volume = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN );
                
                
                volume.setValue(6.0f);
                
                //clip.start();
                
                //return clip;
            } catch (Exception e) {
                System.err.println(e.getMessage());
            }
            
            return clip;
        } catch (LineUnavailableException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return null;
    }
    
    public static Font loadFont(String path, float size){
        try {
            Font myFont = Font.createFont(Font.TRUETYPE_FONT, Main.class.getResourceAsStream(path));
            return myFont.deriveFont(Font.PLAIN, size);
        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
            System.exit(1);
        }
        return null;
    }

    public static String formatSeconds(int timeInSeconds){
        int secondsLeft = timeInSeconds % 3600 % 60;
        int minutes = (int) Math.floor(timeInSeconds % 3600 / 60);
        //int hours = (int) Math.floor(timeInSeconds / 3600);

        //String HH = ((hours       < 10) ? "0" : "") + hours;
        String MM = ((minutes     < 10) ? "0" : "") + minutes;
        String SS = ((secondsLeft < 10) ? "0" : "") + secondsLeft;

        //return HH + ":" + MM + ":" + SS;
        return MM + ":" + SS;
    }   
    

    static final int delay = 1000;
    static final int period = 1000;
    static Timer timer = new Timer();;
    static int interval = 180;
    static boolean intervalIncreased = false; 
    static boolean intervalDecreased = false; 

    
    private static void setInterval(int number){
        if (interval == 1) timer.cancel();
        --interval;
    } 
    
    class RemindTask extends TimerTask {
        Timer timer;
        int seconds;
        RemindTask(Timer currentTimer, int sec){
            timer = currentTimer;
            seconds = sec;
        }
        
        @Override
        public void run() {
           
        }

    
    }
    
    private void startTimer(){
        

        //timer = new Timer();
        
        timer.scheduleAtFixedRate(new TimerTask() {
            public void run() {
                if(interval > 0){

                    setInterval(interval);
                    timerLabel.setText(formatSeconds(interval));

                    if(interval <= 30){
                        timerLabel.setForeground(Color.RED);
                    }
                    else{
                        timerLabel.setForeground(Color.BLACK);
                    }

                    if(intervalIncreased){
                        timerLabel.setForeground(Color.GREEN);
                        intervalIncreased = false;
                    }

                    if(intervalDecreased){
                        timerLabel.setForeground(Color.RED);
                        intervalDecreased = false;
                    }
                }
                else{
                    timerLabel.setText(formatSeconds(0));
                    timerLabel.setForeground(Color.RED);
                }
                
                if(interval <= 0) gameOver(); 
                
            }
        }, delay, period);
    }
    private void printTimer(){
        
        Font Nunito = loadFont("digital.ttf", 28);

        timerLabel.setFont(Nunito);
        timerLabel.setBounds(285,8,80,32);
        timerLabel.setForeground(Color.BLACK);
        timerLabel.setBackground(Color.WHITE);
        timerLabel.setOpaque(true);
    }
    
    private void btnPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPressed
        String letter = (evt.getKeyCode() == 32) ? "" : Character.toString(evt.getKeyChar()).toUpperCase();
        
        try {
            if (letter != null) {
                btnList.get("btn_"+ letter).doClick();
                letter = (letter != "") ? letter : "_";
                processInput(letter);
            }
        } catch (NullPointerException e) {
            System.out.println("NullPointerException");
        }
        
        playMusic("Keyboard.wav").start();
    }//GEN-LAST:event_btnPressed

    private static int currentLetterPosition = 1;
    private   void processInput(String letter){
        
        HashMap<String, JLabel> letters = new HashMap<String, JLabel>();
        letters.put("char_1", char_1);
        letters.put("char_2", char_2);
        letters.put("char_3", char_3);
        letters.put("char_4", char_4);
        letters.put("char_5", char_5);
        letters.put("char_6", char_6);
        letters.put("char_7", char_7);
        letters.put("char_8", char_8);
        
        JLabel currentLetter = letters.get("char_"+ currentLetterPosition);
        System.out.println("currentLetter = "+currentLetter);
        System.out.println("letter = "+letter);
        
        if(currentLetter.getText().equals(letter)){
            currentLetter.setForeground(Color.green);
            currentLetterPosition++;
            
            if(currentLetterPosition > 8){
                System.out.println("Yahoo");
                currentLetterPosition = 1;
                setMagicWord(magicWord());
                interval = interval + 5;
            }
        }
        else{
            if(heartLife > 0){
                heartList.get("heart_"+ heartLife).hide();
                heartLife--;
            }
        }
        
        if(heartLife <= 0){
           gameOver();
        }
    }
    
    private void playAgain(){
        
    }
    
    private void gameOverChoice(){
        fullLife();
    }
    private void gameOver(){
        
        currentLetterPosition = 1;
        //timer.cancel();
        
        int result = JOptionPane.showConfirmDialog(ScreenMap,"Play again?", "GAME OVER!",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        
       
         if(result == 0){
             //startTimer();
             
             interval = 180;
             fullLife();
         }
         else if (result == 1){
             interval = 180;
             fullLife();
             LoginScreen LoginScreen = new LoginScreen();
             LoginScreen.setVisible(true);
             LoginScreen.pack();
             LoginScreen.setLocationRelativeTo(null);
             this.dispose();
         }else {
            System.out.println("none");
         }
         
    }
    
    private static void fullLife(){
        interval = 180;
        setMagicWord(magicWord());
        heartLife = 8;
        heartList.get("heart_1").show();
        heartList.get("heart_2").show();
        heartList.get("heart_3").show();
        heartList.get("heart_4").show();
        heartList.get("heart_5").show();
        heartList.get("heart_6").show();
        heartList.get("heart_7").show();
        heartList.get("heart_8").show();
    }
    
    private static String magicWord;
    
    private static String getMagicWord(){
        return magicWord;
    }
    
    private static void setMagicWord(String newMagicWord){
        String[] word = newMagicWord.split("");
        magicWord = newMagicWord;
                
        char_1.setText(word[0]);
        char_1.setForeground(Color.DARK_GRAY);
        
        char_2.setText(word[1]);
        char_2.setForeground(Color.DARK_GRAY);
        
        char_3.setText(word[2]);
        char_3.setForeground(Color.DARK_GRAY);
        
        char_4.setText(word[3]);
        char_4.setForeground(Color.DARK_GRAY);
        
        char_5.setText(word[4]);
        char_5.setForeground(Color.DARK_GRAY);
        
        char_6.setText(word[5]);
        char_6.setForeground(Color.DARK_GRAY);
        
        char_7.setText(word[6]);
        char_7.setForeground(Color.DARK_GRAY);
        
        char_8.setText(word[7]);
        char_8.setForeground(Color.DARK_GRAY);
    }
    
    private static String magicWord(){
        
        int length = 8;
        //String SALTCHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890 ";
        String SALTCHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890 ";
        StringBuilder salt = new StringBuilder();
        Random rnd = new Random();
        while (salt.length() < length) { // length of the random string.
            int index = (int) (rnd.nextFloat() * SALTCHARS.length());
            char letter = SALTCHARS.charAt(index) != ' ' ? SALTCHARS.charAt(index) : '_';
            salt.append(letter);
        }
        String saltStr = salt.toString();

        return saltStr;
    }
   
    
    /**
     * @param args the command line arguments
     */
    public  void main(String args[]) {
        
        
        
        
        ScreenMap.revalidate();
        
        ScreenMap.repaint();
        
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameScreen().setVisible(true);
            }
        });
    }
    
    //private static String magicWord;
    private static JLabel JWord;
    static int charAtIndex = 0;
    
    static Player player = new Player();
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bg_coins;
    private javax.swing.JLabel bg_heart;
    private javax.swing.JButton btn_;
    private static javax.swing.JButton btn_0;
    private static javax.swing.JButton btn_1;
    private static javax.swing.JButton btn_2;
    private static javax.swing.JButton btn_3;
    private static javax.swing.JButton btn_4;
    private static javax.swing.JButton btn_5;
    private static javax.swing.JButton btn_6;
    private static javax.swing.JButton btn_7;
    private static javax.swing.JButton btn_8;
    private static javax.swing.JButton btn_9;
    private static javax.swing.JButton btn_A;
    private static javax.swing.JButton btn_B;
    private static javax.swing.JButton btn_C;
    private static javax.swing.JButton btn_D;
    private static javax.swing.JButton btn_E;
    private static javax.swing.JButton btn_F;
    private static javax.swing.JButton btn_G;
    private static javax.swing.JButton btn_H;
    private static javax.swing.JButton btn_I;
    private static javax.swing.JButton btn_J;
    private static javax.swing.JButton btn_K;
    private static javax.swing.JButton btn_L;
    private static javax.swing.JButton btn_M;
    private static javax.swing.JButton btn_N;
    private static javax.swing.JButton btn_O;
    private static javax.swing.JButton btn_P;
    private static javax.swing.JButton btn_Q;
    private static javax.swing.JButton btn_R;
    private static javax.swing.JButton btn_S;
    private static javax.swing.JButton btn_T;
    private static javax.swing.JButton btn_U;
    private static javax.swing.JButton btn_V;
    private static javax.swing.JButton btn_W;
    private static javax.swing.JButton btn_X;
    private static javax.swing.JButton btn_Y;
    private static javax.swing.JButton btn_Z;
    private static javax.swing.JLabel char_1;
    private static javax.swing.JLabel char_2;
    private static javax.swing.JLabel char_3;
    private static javax.swing.JLabel char_4;
    private static javax.swing.JLabel char_5;
    private static javax.swing.JLabel char_6;
    private static javax.swing.JLabel char_7;
    private static javax.swing.JLabel char_8;
    private static javax.swing.JLabel heart_1;
    private static javax.swing.JLabel heart_2;
    private static javax.swing.JLabel heart_3;
    private static javax.swing.JLabel heart_4;
    private static javax.swing.JLabel heart_5;
    private static javax.swing.JLabel heart_6;
    private static javax.swing.JLabel heart_7;
    private static javax.swing.JLabel heart_8;
    private javax.swing.JButton hiddenButton;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_heart;
    private javax.swing.JLabel logo_cict;
    private javax.swing.JLabel logo_stiwnu;
    private static java.awt.Label randomTextLabel;
    private javax.swing.JLabel timerLabel;
    // End of variables declaration//GEN-END:variables

}


